version: 2.1

orbs:
  node: circleci/node@4.7.0
jobs:
  test:
    executor:
      name: node/default
      tag: '16.8.0'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn lint
          name: Lint Code
      - run:
          command: yarn test
          name: Run Tests
workflows:
  test_my_app:
    jobs:
      - test
