version: 2.1

orbs:
  node: circleci/node@4.7.0
  heroku: circleci/heroku@1.2.6
jobs:
  test:
    executor:
      name: node/default
      tag: '16.8.0'
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: yarn install
          name: Installing Packages
      - run:
          command: yarn setup
          name: Setup Env
      - save_cache:
          paths:
            - node_modules
            - yarn.lock
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          command: yarn lint
          name: Lint Code
      - run:
          command: yarn test
          name: Run Tests

  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: main
          requires:
            - test
